apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homarr
  name: homarr
  namespace: media
spec:
  template:
    metadata:
      labels:
        app: homarr
    spec:
      containers:
        - image: ghcr.io/ajnart/homarr:latest
          imagePullPolicy: Always
          name: homarr
          env:
          - name: TZ
            value: "Europe/Helsinki"
          - name: DISABLE_ANALYTICS
            value: "True"
          ports:
          - name: homarr-port
            containerPort: 7575
            protocol: TCP
          volumeMounts:
          - name: homarr-config
            mountPath: /app/data/configs
          - name: homarr-media
            mountPath: /app/public/icons
          - name: homarr-data
            mountPath: /data
          resources:
            requests:
              memory: 350Mi
              cpu: 10m
            limits:
              memory: 450Mi
              cpu: 350m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: homarr-config
        persistentVolumeClaim:
          claimName: "homarr-config"
      - name: homarr-media
        persistentVolumeClaim:
          claimName: "homarr-media"
      - name: homarr-data
        persistentVolumeClaim:
          claimName: "homarr-data"
  selector:
    matchLabels:
      app: homarr