apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: control-ips
  namespace: metallb-system
spec:
  addresses:
  # The IP addresses that MetalLB will hand out for services in the 'control-plane' role.
  - 192.168.2.32/32
  - 192.168.2.164/32
