apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-admin-credentials
  namespace: git-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: gitea-admin-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: gitea-admin-credentials
      property: password
  - secretKey: email
    remoteRef:
      key: gitea-admin-credentials
      property: email