---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux-Kustomizations
  - ./rook-ceph/ks.yaml
  - ./nfd/ks.yaml
  - https://raw.githubusercontent.com/intel/intel-device-plugins-for-kubernetes/main/deployments/nfd/overlays/node-feature-rules/node-feature-rules.yaml
  - ./intel-gpu-plugin/ks.yaml