apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  capacity:
    storage: 100000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: external-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: 192.168.2.32
