apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-joplin
  namespace: cnpg-system
spec:
  # enableSuperuserAccess: true
  # superuserSecret:
  #   name: joplin-superuser-password
  instances: 1
  bootstrap:
    initdb:
      database: joplin
      owner: joplin
      dataChecksums: true
      secret:
        name: joplin-user-password
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0
  resources:
    requests:
      memory: 300Mi
      cpu:  150m
    limits:
      memory: 300Mi
      cpu: 150m
  storage:
    size: 5Gi
