apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-gitea
  namespace: cnpg-system
spec:
  # enableSuperuserAccess: true
  # superuserSecret:
  #   name: gitea-superuser-password
  instances: 1
  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      dataChecksums: true
      secret:
        name: gitea-user-password
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0
  resources:
    requests:
      memory: 300Mi
      cpu:  150m
    limits:
      memory: 300Mi
      cpu: 150m
  storage:
    size: 20Gi
