---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app resume
  namespace: flux-system
spec:
  targetNamespace: gregbob
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/cluster0/kubernetes/apps/gregbob/gregbob/resume/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 3m
  retryInterval: 1m
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gregblog
  namespace: flux-system
spec:
  targetNamespace: gregbob
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./clusters/cluster0/kubernetes/apps/gregbob/gregbob/blog/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 3m
  retryInterval: 1m
  timeout: 1m
